deleted unused elements + update Dockerfile for both main dir

diff --git a/frontend/Dockerfile b/frontend/Dockerfile
--- a/frontend/Dockerfile
+++ b/frontend/Dockerfile
@@ -1,35 +1,50 @@
-# Utilisation d'une image Node.js
-FROM node:alpine
+FROM node:18-alpine AS base
 
-# Créer un répertoire de travail
+# 1. Install dependencies only when needed
+FROM base AS deps
+# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
+RUN apk add --no-cache libc6-compat
+
 WORKDIR /app
 
-# Installer PM2
-RUN npm install --global pm2
+# Install dependencies based on the preferred package manager
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
-# Copier les dépendances de l'application
-COPY package.json yarn.lock ./
-
-# Installer les dépendances
-RUN npm install --production
-
-# Copier le reste des fichiers de l'application
+# 2. Rebuild the source code only when needed
+FROM base AS builder
+WORKDIR /app
+COPY --from=deps /app/node_modules ./node_modules
 COPY . .
-
-#RUN npx prisma generate
-
-# Construction de l'application
+# This will do the trick, use the corresponding env file for each environment.
+COPY .env.local .env
 RUN npm run build
 
-USER node
+# 3. Production image, copy all the files and run next
+FROM base AS runner
+WORKDIR /app
 
-# Exposer le port sur lequel l'application fonctionnera
+ENV NODE_ENV=production
+
+RUN addgroup -g 1001 -S nodejs
+RUN adduser -S nextjs -u 1001
+
+COPY --from=builder /app/public ./public
+
+# Automatically leverage output traces to reduce image size
+# https://nextjs.org/docs/advanced-features/output-file-tracing
+COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
+COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
+COPY --from=builder --chown=nextjs:nodejs /app/node_modules ./node_modules
+
+USER nextjs
+
 EXPOSE 3000
 
-# Commande pour démarrer l'application
-CMD [ "pm2-runtime", "npm", "--", "start" ]
-
-# Stage 1, based on Nginx, to have only the compiled app, ready for production with Nginx
-
-#COPY --from=build-stage /app/.next/ /var/www/flickpulse/
+CMD HOSTNAME=localhost node server.js
 
